export const DEMO = 'DEMO';
export const SIGNUP_PAYLOAD = 'SIGNUP_PAYLOAD';
export const PATIENT_DATA = 'PATIENT_DATA';
export const DOCTOR_DATA = 'DOCTOR_DATA';
export const BOOKING_DATA = 'BOOKING_DATA';
export const LOCATION_INFO = 'LOCATION_INFO';
export const DEL_NOTIFICATION = 'DEL_NOTIFICATION';
export const ADD_CARD = 'ADD_CARD';
export const DATA_GOOGlEAUTH = 'DATA_GOOGlEAUTH';
export const DATA_FBAUTH = 'DATA_FBAUTH';
export const DATA_APPLEAUTH = 'DATA_APPLEAUTH';
export const SIGNUPAS = 'SIGNUPAS';
export const SIGNUPASID = 'SIGNUPASID'

// export const DOCTOR_NAME = 'DOCTOR_NAME';
// export const SPECIALITY = 'SPECIALITY';
// export const RATING_COUNT = 'RATING_COUNT';
// export const EXPERIENCE = 'EXPERIENCE';
// export const REVIEWS = 'REVIEWS';
// export const FEE = 'FEE';