export const FONT_FAMILY = {
    MontserratBlack : 'Montserrat-Black',
    MontserratBlackItalic: 'Montserrat-BlackItalic',
    MontserratBold: 'Montserrat-Bold',
    MontserratBoldItalic: 'Montserrat-BoldItalic',
    MontserratExtraBold: 'Montserrat-ExtraBold',
    MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    MontserratExtraLight: 'Montserrat-ExtraLight',
    MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
    MontserratItalic: 'Montserrat-Italic',
    MontserratLight: 'Montserrat-Light',
    MontserratLightItalic: 'Montserrat-LightItalic',
    MontserratMedium: 'Montserrat-Medium',
    MontserratMediumItalic: 'Montserrat-MediumItalic',
    MontserratRegular: 'Montserrat-Regular',
    MontserratSemiBold: 'Montserrat-SemiBold',
    MontserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
    MontserratThin: 'Montserrat-Thin',
    MontserratThinItalic: 'Montserrat-ThinItalic',
    Montserrat: 'Montserrat',
};

export const RouteNames = {
    splash: 'splash',
    introScreens: 'introScreens',
    optionScreen: 'optionScreen',
    login: 'login',
    signup: 'signup',
    forgotpassword: 'forgotpassword',
    passVerification: 'passVerification',
    resetPass: 'resetPass',
    providerBottomTabs: 'providerBottomTabs',    
    userBottomTabs: 'userBottomTabs',
    userDrawer: 'userDrawer',
    jobDetailAndPayment: 'jobDetailAndPayment',
    userJobDetail: 'userJobDetail',
    paymentDone: 'paymentDone',
    providerDrawer: 'providerDrawer',
    editProfile: 'editProfile',
    profileTabStack: 'profileTabStack',
    chatTabStack: 'chatTabStack',
    addJobStack: 'addJobStack',
    homeTabStack: 'homeTabStack',
    addJob: 'addJob',
    addJobProvider: 'addJobProvider',
    addLoads: 'addLoads',
    userHome: 'userHome',
    getEstimatePrice: 'getEstimatePrice',
    getRequirements: 'getRequirements',
    getRequirementsDetail: 'getRequirementsDetail',
    avgEstimatePrice: 'avgEstimatePrice',
    notification: 'notification',
    famousVendors: 'famousVendors',
    calculateExpense: 'calculateExpense',

  };